#%RAML 1.0 Trait
headers:
  client_id:
    displayName: Client Id
    description: Llave del cliente
    type: string
    required: true
  client_secret:
    displayName: Client Secreta
    description: Llave secreta del cliente
    type: string
    required: true